### ISSUE TITLE
may you help find code for Interaction discovery for logistic regression

### ISSUE THREAD

**Issue by Sandy4321** [adimajo/scoringTools#4]
great post
https://adimajo.github.io/interaction_screening.html
Interaction discovery for logistic regression
may you help find code for this post pls?

**Comment by adimajo** [comment]
Thanks!
The code for Section "Simulated data" is here: https://github.com/adimajo/manuscrit_these/tree/master/R_CODE_FIGURES/chapitre5

The code for benchmark data is here: https://github.com/adimajo/manuscrit_these/blob/master/R_CODE_FIGURES/chapitre4/essai_glmdisc.R
