### ISSUE TITLE
Introduction to Credit Scoring   in English please ? 

### ISSUE THREAD

**Issue by Sandy4321** [adimajo/scoringTools#5]
great post
Introduction to Credit Scoring
https://adimajo.github.io/scoring.html

only 
do you have something similar in English? 
or / and others authors  material ?

**Comment by adimajo** [comment]
Thanks.
I didn't write any in English.
This one seems OK but relatively (too) simple: https://towardsdatascience.com/intro-to-credit-scorecard-9afeaaa3725f
